# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'All Things Math' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for All Things Math
  pod 'iosMath'

end
